name: Tests

on: [push]

jobs:
  buildJava14:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Run unit tests
      run: ./gradlew test
    - name: Trigger BE build
      run: |
        git clone --depth=1 --branch=master https://github.com/Anuken/MindustryBuilds ../MindustryBuilds
        cd ../MindustryBuilds
        BNUM=$(($GITHUB_RUN_NUMBER + 20000))
        git tag ${BNUM}
        git config --global user.name "Build Uploader"
        git push https://Anuken:${{ secrets.API_TOKEN_GITHUB }}@github.com/Anuken/MindustryBuilds ${BNUM}
